import { stubAsset } from "./stub.ts";
import type { Asset } from "../schema.ts";

/**
 * Coverage set for Product 1. Structure (issuer, wrapper, gates) is estimated
 * from widely published product descriptions. Every mark (NAV, APY, SOFR,
 * token address, ISIN) is unavailable — unknown > wrong.
 */
export const rawAssets: Asset[] = [
  stubAsset({
    id: "buidl",
    name: "BlackRock USD Institutional Digital Liquidity Fund",
    symbol: "BUIDL",
    asset_class: "treasury_fund",
    wrapper_type: "reg_d",
    issuer: "BlackRock",
    manager: "BlackRock",
    custodian: "BNY Mellon",
    transfer_agent: "Securitize",
    benchmark: "SOFR",
    nav_model: "stable_1",
    yield_type: "distributing",
    gates: ["us_qp", "allowlist"],
    us_persons: "allowed",
    retail: "blocked",
    eligibility_notes:
      "Qualified purchaser / permissioned transfer — confirm against current docs. Not a determination of eligibility.",
    redeemability: "permissioned",
    liquidity_notes:
      "Primary mint/redeem dominated; secondary may be thin. Estimated from public product shape.",
    website: "https://www.blackrock.com",
  }),
  stubAsset({
    id: "ousg",
    name: "Ondo Short-Term US Government Treasuries",
    symbol: "OUSG",
    asset_class: "treasury_fund",
    wrapper_type: "open_ended_fund",
    issuer: "Ondo",
    manager: "Ondo Finance",
    benchmark: "SOFR",
    nav_model: "continuous",
    yield_type: "accumulating",
    gates: ["us_qp", "allowlist", "kyc"],
    us_persons: "allowed",
    retail: "blocked",
    eligibility_notes:
      "US qualified purchaser / accredited channel is the public shape. Confirm against current Ondo docs.",
    redeemability: "t_plus",
    liquidity_notes: "Fund-style subscription/redemption. Estimated.",
    website: "https://ondo.finance",
  }),
  stubAsset({
    id: "usdy",
    name: "Ondo US Dollar Yield",
    symbol: "USDY",
    asset_class: "treasury_fund",
    wrapper_type: "tokenized_note",
    issuer: "Ondo",
    manager: "Ondo Finance",
    benchmark: "SOFR",
    nav_model: "continuous",
    yield_type: "accumulating",
    gates: ["non_us", "kyc"],
    us_persons: "blocked",
    retail: "unknown",
    eligibility_notes:
      "Publicly described as a non-US product. US persons blocked at docs level. Not legal advice.",
    redeemability: "t_plus",
    liquidity_notes: "Permissioned mint/redeem; secondary venues not sourced.",
    website: "https://ondo.finance",
  }),
  stubAsset({
    id: "ustb",
    name: "Superstate Short Duration US Government Securities Fund",
    symbol: "USTB",
    asset_class: "treasury_fund",
    wrapper_type: "open_ended_fund",
    issuer: "Superstate",
    manager: "Superstate",
    benchmark: "SOFR",
    nav_model: "periodic_daily",
    yield_type: "accumulating",
    gates: ["us_qp", "allowlist", "kyc"],
    us_persons: "allowed",
    retail: "blocked",
    eligibility_notes:
      "Registered-fund / qualified-purchaser shape from public materials. Confirm current offering docs.",
    redeemability: "permissioned",
    liquidity_notes: "Fund subscription/redemption. Estimated.",
    website: "https://superstate.co",
  }),
  stubAsset({
    id: "benji",
    name: "Franklin OnChain U.S. Government Money Fund",
    symbol: "BENJI",
    asset_class: "cash_mgmt",
    wrapper_type: "forty_act_mmf",
    issuer: "Franklin Templeton",
    manager: "Franklin Templeton",
    benchmark: "SOFR",
    nav_model: "stable_1",
    yield_type: "distributing",
    gates: ["kyc"],
    us_persons: "allowed",
    retail: "allowed",
    eligibility_notes:
      "40 Act money fund (FOBXX) publicly offered via brokers — still KYC'd. v0 will not claim likely_eligible.",
    redeemability: "daily",
    liquidity_notes: "Registered MMF; daily liquidity is the public shape. Estimated.",
    website: "https://www.franklintempleton.com",
  }),
  stubAsset({
    id: "spiko_ustbl",
    name: "Spiko US T-Bills Money Market Fund",
    symbol: "USTBL",
    asset_class: "treasury_fund",
    wrapper_type: "ucits_mmf",
    issuer: "Spiko",
    manager: "Spiko",
    benchmark: "SOFR",
    nav_model: "stable_1",
    yield_type: "accumulating",
    gates: ["non_us", "kyc"],
    us_persons: "blocked",
    retail: "unknown",
    eligibility_notes:
      "UCITS MMF. Publicly a European product; US persons treated as blocked at docs level until sourced otherwise.",
    redeemability: "daily",
    liquidity_notes: "UCITS MMF daily dealing is the public shape. Estimated.",
    website: "https://www.spiko.finance",
  }),
  stubAsset({
    id: "spiko_eutbl",
    name: "Spiko Euro T-Bills Money Market Fund",
    symbol: "EUTBL",
    asset_class: "treasury_fund",
    wrapper_type: "ucits_mmf",
    issuer: "Spiko",
    manager: "Spiko",
    benchmark: null,
    nav_model: "stable_1",
    yield_type: "accumulating",
    gates: ["non_us", "kyc"],
    us_persons: "blocked",
    retail: "unknown",
    eligibility_notes:
      "EUR UCITS MMF. US persons blocked at docs level. Benchmark is not SOFR; spread vs SOFR remains null.",
    redeemability: "daily",
    liquidity_notes: "UCITS MMF daily dealing is the public shape. Estimated.",
    website: "https://www.spiko.finance",
  }),
  stubAsset({
    id: "syrup_usdc",
    name: "Maple syrupUSDC",
    symbol: "syrupUSDC",
    asset_class: "private_credit",
    wrapper_type: "unknown",
    issuer: "Maple",
    manager: "Maple Finance",
    benchmark: "SOFR",
    nav_model: "continuous",
    yield_type: "accumulating",
    gates: ["kyc", "unknown"],
    us_persons: "unknown",
    retail: "unknown",
    eligibility_notes:
      "On-chain private credit wrapper. Geo/KYC gates exist in practice; v0 will not claim open access.",
    redeemability: "unknown",
    liquidity_notes: "Secondary and withdrawal windows not sourced.",
    website: "https://maple.finance",
  }),
  stubAsset({
    id: "jtrsy",
    name: "Janus Henderson Anemoy Treasury Fund (JTRSY)",
    symbol: "JTRSY",
    asset_class: "treasury_fund",
    wrapper_type: "unknown",
    issuer: "Janus Henderson",
    manager: "Janus Henderson",
    benchmark: "SOFR",
    nav_model: "unknown",
    yield_type: "unknown",
    gates: ["unknown"],
    us_persons: "unknown",
    retail: "unknown",
    eligibility_notes:
      "Identity is a seed placeholder (schema: swap to acred if better sourced). Structure, wrapper, and gates unverified.",
    redeemability: "unknown",
    liquidity_notes: "Not sourced.",
    website: "https://www.janushenderson.com",
  }),
  stubAsset({
    id: "xaut",
    name: "Tether Gold",
    symbol: "XAUt",
    asset_class: "commodity",
    wrapper_type: "unknown",
    issuer: "Tether",
    manager: "Tether",
    benchmark: null,
    nav_model: "continuous",
    yield_type: "unknown",
    gates: ["unknown"],
    us_persons: "unknown",
    retail: "unknown",
    eligibility_notes:
      "Gold-backed token, not a cash-management fund. Venue KYC varies. v0 will not claim open eligibility.",
    redeemability: "unknown",
    liquidity_notes:
      "Secondary trading exists; primary redeemability and venues not sourced in v0.",
    website: "https://gold.tether.to",
  }),
];

export const COVERAGE_IDS = [
  "buidl",
  "ousg",
  "usdy",
  "ustb",
  "benji",
  "spiko_ustbl",
  "spiko_eutbl",
  "syrup_usdc",
  "jtrsy",
  "xaut",
] as const;
