/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as YieldsRouteImport } from './routes/yields'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as V0EligibilityRouteImport } from './routes/v0.eligibility'
import { Route as V0HealthRouteImport } from './routes/v0.health'
import { Route as V0YieldsRouteImport } from './routes/v0.yields'
import { Route as V0AssetsIndexRouteImport } from './routes/v0.assets.index'
import { Route as V0AssetsIdRouteImport } from './routes/v0.assets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const YieldsRoute = YieldsRouteImport.update({
  id: '/yields',
  path: '/yields',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V0EligibilityRoute = V0EligibilityRouteImport.update({
  id: '/v0/eligibility',
  path: '/v0/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const V0HealthRoute = V0HealthRouteImport.update({
  id: '/v0/health',
  path: '/v0/health',
  getParentRoute: () => rootRouteImport,
} as any)
const V0YieldsRoute = V0YieldsRouteImport.update({
  id: '/v0/yields',
  path: '/v0/yields',
  getParentRoute: () => rootRouteImport,
} as any)
const V0AssetsIndexRoute = V0AssetsIndexRouteImport.update({
  id: '/v0/assets/',
  path: '/v0/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const V0AssetsIdRoute = V0AssetsIdRouteImport.update({
  id: '/v0/assets/$id',
  path: '/v0/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eligibility': typeof EligibilityRoute
  '/yields': typeof YieldsRoute
  '/assets/$id': typeof AssetsIdRoute
  '/v0/eligibility': typeof V0EligibilityRoute
  '/v0/health': typeof V0HealthRoute
  '/v0/yields': typeof V0YieldsRoute
  '/v0/assets/$id': typeof V0AssetsIdRoute
  '/v0/assets/': typeof V0AssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eligibility': typeof EligibilityRoute
  '/yields': typeof YieldsRoute
  '/assets/$id': typeof AssetsIdRoute
  '/v0/eligibility': typeof V0EligibilityRoute
  '/v0/health': typeof V0HealthRoute
  '/v0/yields': typeof V0YieldsRoute
  '/v0/assets/$id': typeof V0AssetsIdRoute
  '/v0/assets': typeof V0AssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eligibility': typeof EligibilityRoute
  '/yields': typeof YieldsRoute
  '/assets/$id': typeof AssetsIdRoute
  '/v0/eligibility': typeof V0EligibilityRoute
  '/v0/health': typeof V0HealthRoute
  '/v0/yields': typeof V0YieldsRoute
  '/v0/assets/$id': typeof V0AssetsIdRoute
  '/v0/assets/': typeof V0AssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eligibility'
    | '/yields'
    | '/assets/$id'
    | '/v0/eligibility'
    | '/v0/health'
    | '/v0/yields'
    | '/v0/assets/$id'
    | '/v0/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eligibility'
    | '/yields'
    | '/assets/$id'
    | '/v0/eligibility'
    | '/v0/health'
    | '/v0/yields'
    | '/v0/assets/$id'
    | '/v0/assets'
  id:
    | '__root__'
    | '/'
    | '/eligibility'
    | '/yields'
    | '/assets/$id'
    | '/v0/eligibility'
    | '/v0/health'
    | '/v0/yields'
    | '/v0/assets/$id'
    | '/v0/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EligibilityRoute: typeof EligibilityRoute
  YieldsRoute: typeof YieldsRoute
  AssetsIdRoute: typeof AssetsIdRoute
  V0EligibilityRoute: typeof V0EligibilityRoute
  V0HealthRoute: typeof V0HealthRoute
  V0YieldsRoute: typeof V0YieldsRoute
  V0AssetsIdRoute: typeof V0AssetsIdRoute
  V0AssetsIndexRoute: typeof V0AssetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yields': {
      id: '/yields'
      path: '/yields'
      fullPath: '/yields'
      preLoaderRoute: typeof YieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v0/eligibility': {
      id: '/v0/eligibility'
      path: '/v0/eligibility'
      fullPath: '/v0/eligibility'
      preLoaderRoute: typeof V0EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v0/health': {
      id: '/v0/health'
      path: '/v0/health'
      fullPath: '/v0/health'
      preLoaderRoute: typeof V0HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v0/yields': {
      id: '/v0/yields'
      path: '/v0/yields'
      fullPath: '/v0/yields'
      preLoaderRoute: typeof V0YieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v0/assets/': {
      id: '/v0/assets/'
      path: '/v0/assets'
      fullPath: '/v0/assets/'
      preLoaderRoute: typeof V0AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v0/assets/$id': {
      id: '/v0/assets/$id'
      path: '/v0/assets/$id'
      fullPath: '/v0/assets/$id'
      preLoaderRoute: typeof V0AssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EligibilityRoute: EligibilityRoute,
  YieldsRoute: YieldsRoute,
  AssetsIdRoute: AssetsIdRoute,
  V0EligibilityRoute: V0EligibilityRoute,
  V0HealthRoute: V0HealthRoute,
  V0YieldsRoute: V0YieldsRoute,
  V0AssetsIdRoute: V0AssetsIdRoute,
  V0AssetsIndexRoute: V0AssetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
